# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# sum of a set of numbers using for loop. 

l=[]
n=int(input("enter the number of elemets"))
print("enter the elements")
for i in range(1,n+1):
  ele=int(input())
  l.append(ele)
print(l)
sum=0
for i in range(0,n):
  sum=sum+l[i]
print("the sum is \n")
print(sum)

# sum of first n natural numbers using recursion.

def sum(num):
  if num<=1:
    return num
  else:
    return num+sum(num-1)
  

n=int(input("enter the limit"))
print("the sum is:\n",sum(n))

#Use for-else construct to print if the given n numbers are prime or not.
l=[]
n=int(input("enter the limit"))
print("enter the numbers")
for k in range(1,n+1):
  ele=int(input())
  l.append(ele)
print("the numbers are:")
print(l)

for i in l:
  for j in range(2,n+1):
    if(i%j==0):
      print(i," is not prime")
      break
    else:
      print(i," is prime")
      break

#sum of digits of a number using while.
r=0
n=int(input("enter the number"))
while(n>0):
  dig=n%10
  r+=dig
  n=n//10
print("The sum of digit is:\n")
print(r)

#to check if a given number is a palindrome or not

n=int(input("enter the number"))
temp=n
rev=0
while(n>0):
  dig=n%10
  rev=rev*10+dig
  n=n//10
if(temp==rev):
    print("The number is a palindrome!")
else:
    print("The number isn't a palindrome!")

